# Generated by Django 3.2.6 on 2021-08-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='google_books_id',
            field=models.CharField(default='---------', max_length=250),
            preserve_default=False,
        ),
    ]
