# Generated by Django 3.2.6 on 2021-08-14 04:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vinyls',
            fields=[
                ('vinyl_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('artists', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('picture_url', models.CharField(max_length=2040)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinyls.genres')),
            ],
        ),
    ]
