# Generated by Django 3.2.6 on 2021-08-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_games_age_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='number_players',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
