# Generated by Django 3.2.6 on 2021-08-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_games_number_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='time_of_play',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
