# Generated by Django 3.2.6 on 2021-08-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_games_time_of_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='board_game_atlas_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
